import { GetServerSideProps } from 'next'
import Head from 'next/head'
import { useEffect } from 'react'
import { Header,Hero,Row } from 'src/components'
import { IMove } from 'src/interfaces/app.interfaces'
import { API_REQUEST } from 'src/services/api.services'

export default function Home({tranding,topRated}:HomeProps):JSX.Element {
  console.log(topRated);
  



  // useEffect(()=>{
  //   fetch(API_REQUEST.trending)
  //   .then(res=>res.json())
  //   .then(data=>console.log(data)
  //   ).catch(data=>console.log('api xato')
  //   );

  // },[])

  return (
    <div className='relative h-[200vh]'>
      <Head>
        <title>Home-MoveApp</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.svg " />
      </Head>
      <Header /> 
     <main className='relative pl-4 pb-24 lg:space-y-24 lg:pl-16'>
      <Hero tranding={tranding}/>
      <section>
          <Row title='Top Rated' movies={topRated}/>
       </section>
     </main>
    </div>
  )
}

export const getServerSideProps:GetServerSideProps<HomeProps>=async()  =>{
  const tranding=await fetch(API_REQUEST.trending).then(res=>res.json());
  const topRated=await fetch(API_REQUEST.top_rtted).then(res=>res.json());

      // if(tranding.results.length)
      // {
      //   //1
      //   return {
      //   //  redirect:{
      //   //   destination:"/account",
      //   //  }
      //   //2
      //     notFound:true
      //   }
      // }
  return {
  props:{
    tranding:tranding.results,
    topRated:topRated.results,
  },
}
};


interface HomeProps {
  tranding:IMove[];
  topRated:IMove[]
}